var express = require('express');
var router = express.Router();
const BlogIndexController = require('../controllers/BlogIndexController')
const TimeLineController = require("../controllers/TimeLineController")
const BlogCommentController = require("../controllers/BlogCommentController")
const BlogTypeController = require("../controllers/BlogTypeController")
const UsersController = require("../controllers/UsersController")
const rightsController = require("../controllers/rightsController")
const RolesController = require("../controllers/RolesController")
const childrenModel = require("../controllers/ChildrenController")
const RegionModel= require("../controllers/RegionController")
/* GET users listing. */
router.get('/', function(req, res, next) {
  res.send('respond with a resource');
});
router.get("/blogindex",BlogIndexController.getBlogIndex)
router.get("/blogindex/blogtype",BlogTypeController.getBlogType)
router.get("/blogindex/number",BlogIndexController.getBlogNumber)
router.get("/typeblog",BlogIndexController.getTypeBlog)
router.get("/timeline",TimeLineController.getTimeLine)
router.post("/blogindex",BlogIndexController.postBlog)
router.get("/blogComment",BlogCommentController.getBlogComment)
router.get("/blogIndex/viewsnumber",BlogIndexController.getBlogViewsNumber)
router.get("/blogIndex/commentnumber",BlogIndexController.getBlogCommentNumber)
router.post("/blogComment",BlogCommentController.postBlogComment)
router.get("/blogindex/hotblog",BlogIndexController.getHotBlogTitle)
router.delete("/blogindex",BlogIndexController.delBlogIndex)
router.get("/bloginfo",BlogIndexController.getBlogInfo)
router.patch("/newinfo",BlogIndexController.patchBlogInfo)
router.post("/blogtype",BlogTypeController.postBlogType)
router.delete("/blogtype",BlogTypeController.delBlogType)
router.patch ("/blogtype",BlogTypeController.patchBlogType)
router.post("/login",UsersController.postUserInfo)
router.get("/rights",rightsController.getrights)
router.get("/roles",RolesController.getRoles)
router.delete("/roles",RolesController.delRoles)
router.get('/users',UsersController.getUserInfo)
router.patch('/roles/:id',RolesController.patchRoles)
router.get('/rights/children',rightsController.getRightsChildren)
router.delete("/rights/:id",rightsController.delRights)
router.get("/children",childrenModel.getChildren)
router.get("/regions",RegionModel.getRegions)
router.delete('/children/:id',childrenModel.delChildren)
module.exports = router;
